name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    runs-on: self-hosted # Runs on our locally hosted machine

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
    - name: Tester
      run: |
        ./build/tester
    - name: Radix Spline
      run: |
        ./build/tester
