language: cpp
dist: bionic
addons:
  apt:
    packages:
      - libc++-8-dev
      - libc++abi-8-dev
compiler:
  - clang
  - gcc
script:
  - export LD_LIBRARY_PATH=$(if [[ $CXX == "clang++" ]]; then echo -n '/usr/local/clang/lib'; fi)
  - cmake .
  - make
  - ./test/tests